name: Firebase Deploy

on:
    push:
        branches:
            - master
    paths-ignore:
        - docs
        - planning

jobs:
    firebase-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                  node-version: '12.x'        
            - run: cd client && yarn install
            - run: cd client && yarn run build:prod
            - uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                  PROJECT_PATH: ./client
