name: Continous Integration

on:
    pull_request:
        branches: [master]

jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                  node-version: '12.x'
            - run: cd client && yarn install --frozen-lockfile
            - run: cd client && yarn build
