version: "3.7"

services:
  tahiti:
    image: tahiti
    volumes:
      - "./client/logs:/client/logs:rw"
      - "./client/env:/client/env:rw"
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    command: yarn start:prod
