export default Object.freeze({
  ADAMANTIUM_ARCHIVE_A: process.env.NEXT_PUBLIC_ADAMANTIUM_ARCHIVE_A,
  ADAMANTIUM_ARCHIVE_B: process.env.NEXT_PUBLIC_ADAMANTIUM_ARCHIVE_b,
  ACTIVE: process.env.NEXT_PUBLIC_INFINITY_A,
});
