name: Development CI/CD

on:
  pull_request_target:
    types: [reopened, ready_for_review, labeled, synchronize]

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  issues: write
  discussions: write
  packages: read
  pull-requests: write
  repository-projects: read
  security-events: write
  statuses: read

jobs:
  setup:
    uses: Monday-Morning/project-tahiti/.github/workflows/setup.yml@main
    with:
      setup_dev: true

  eslint:
    needs: setup
    uses: Monday-Morning/project-tahiti/.github/workflows/eslint.yml@main
    with:
      config_path: ./.eslintrc.json
      ignore_path: ./.eslintignore
      file_path: "./"

  prettier:
    needs: setup
    uses: Monday-Morning/project-tahiti/.github/workflows/prettier.yml@main
    with:
      file_pattern: "./client/."
      config_path: "./client/.prettierrc"
      ignore_path: "./client/.prettierignore"
      fail_on_error: true

  analyze:
    needs: [eslint, prettier]
    if: contains(github.event.pull_request.labels.*.name, 'safe-for-checks')
    uses: Monday-Morning/project-tahiti/.github/workflows/analyze.yml@main
