name: ESLint Check

on:
  workflow_call:
    inputs:
      config_path:
        required: true
        type: string
      ignore_path:
        required: true
        type: string
      file_path:
        required: true
        type: string

jobs:
  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Use Actions Dev Cache
        uses: actions/cache@v2
        id: yarn-dev-cache
        if: ${{ inputs.setup_dev }}
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-dev-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dev Dependencies
        if: ${{ inputs.setup_dev }} && steps.yarn-dev-cache.outputs.cache-hit != 'true'
        run: cd client && yarn install

      - name: Install ESLint
        run: yarn global add eslint

      - name: Run ESLint
        run: |
        cd client
        yarn next lint -c ${{ inputs.config_path }} --ignore-path ${{ inputs.ignore_path }} --output-file eslint_report.txt ${{ inputs.file_path }}

      - name: ESLint Output
        if: ${{ failure() }}
        shell: bash
        run: |
          cat eslint_report.txt
