name: ESLint Check

on:
  workflow_call:
    inputs:
      config_path:
        required: true
        type: string
      ignore_path:
        required: true
        type: string
      file_path:
        required: true
        type: string

jobs:
  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Prepared Repository
        uses: actions/download-artifact@v2
        with:
          name: setup-app

      - name: Unzip Artifact
        run: unzip app.zip

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Install ESLint
        run: yarn global add eslint

      - name: Run ESLint
        run: eslint -c ${{ inputs.config_path }} --ignore-path ${{ inputs.ignore_path }} --output-file eslint_report.txt ${{ inputs.file_path }}

      - name: ESLint Output
        if: ${{ failure() }}
        shell: bash
        run: |
          cat eslint_report.txt
