name: Lint and Format Check

on:
  pull_request_review:
    types: [submitted]

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  issues: write
  discussions: write
  packages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install Dependencies
        run: cp client/package.json ./ && yarn install

      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint_flags: "client/"

  # prettier:
  #   name: Prettier Check
  #   runs-on: ubuntu-latest
  #   if: github.event.review.state == 'approved'
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2
  #       with:
  #         ref: ${{ github.head_ref }}

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: "14"

  #     - name: Install Dependencies
  #       run: cp client/package.json ./ && yarn install

  #     - name: Prettify code
  #       uses: creyD/prettier_action@dev
  #       with:
  #         prettier_options: -c ./client/.prettierrc
  #         file_pattern: ./client/.
  #         dry: true
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
