name: Prettier Check

on:
  workflow_call:
    inputs:
      file_pattern:
        required: true
        type: string
      config_path:
        required: true
        type: string
      ignore_path:
        required: true
        type: string
      fail_on_error:
        required: true
        type: boolean

jobs:
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Use Actions Dev Cache
        uses: actions/cache@v2
        id: yarn-dev-cache
        if: ${{ inputs.setup_dev }}
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-dev-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dev Dependencies
        if: ${{ inputs.setup_dev }} && steps.yarn-dev-cache.outputs.cache-hit != 'true'
        run: cd client && yarn install

      - name: Run Prettier
        id: prettier-run
        uses: rutajdash/prettier-cli-action@v1.0.0
        with:
          file_pattern: ${{ inputs.file_pattern }}
          config_path: ${{ inputs.config_path }}
          ignore_path: ${{ inputs.ignore_path }}
          fail_on_error: ${{ inputs.fail_on_error }}

      - name: Prettier Output
        if: ${{ failure() }}
        shell: bash
        run: |
          echo "The following files are not formatted:"
          echo "${{ steps.prettier-run.outputs.prettier_output }}"
